### ISSUE TITLE
Issues with animes with more than 9 themes

### ISSUE THREAD

**Issue by Eastborn** [LeNitrous/anime-themes#5]
In theme.ts i found that your regex to extract if the theme is an opening/ending the number and version is:

/src/theme.ts
```ts
const parts = data.themeType.match(/(OP|ED)(\d)?( V(\d))?/);
```

Although some anime haave more than 9 themes thus having a number with more than 1 \d
example: https://themes.moe/api/themes/269 -> Ending 28 ->
```json
{
    "themeType": "ED28 V2",
    "themeName": "Haruka Kanata",
    "mirror": {
      "mirrorURL": "https://animethemes.moe/video/Bleach-ED28v2.webm",
      "priority": 3,
      "notes": ""
    }
}
```

this is easily fixable by changing it to:

```ts
const parts = data.themeType.match(/(OP|ED)(\d+)?( V(\d+))?/);
```

by adding the + after /d you say it should find 1 or more digits

**Comment by LeNitrous** [comment]
Thank you for your findings! This should go live in a few.
